### PR TITLE
Support for Community, Pro, Enterprise [15.0, 17.0)

### PR DESCRIPTION
**Pull request by PTKu**
Add support for other editions of Visual Studio: Community, Pro, Enterprise [15.0, 17.0)
#63

@Roald87 I did not get change to test on all version/editions.

### CODE REVIEW

**Comment by Roald87** [comment]
Hi @PTKu! Thanks for the PR. For which versions did you test it? I do not have access to the Pro and Enterprise versions. VS2019 I would have to install. Hope I have enough space for it 🤔.

Why does it say the commit is from Ron Nielsen?
afbeelding

**Comment by PTKu** [comment]
Hi @Roald87  it is strange when I commit from my laptop (newly installed) it says it's committed by that guy... I have to review git settings... 

As per testing... I was unable to fully compile due to a problem with TCatSysManagerLib.dll. That's why I PR this as a draft... will try to fix it on Monday if I get a chance... and test it on Pro properly.

Anyways, I never had a problem with an extension adding edition (there could be a problem with versions, though)... so better we test it...

**Comment by Roald87** [comment]
> Hi @Roald87 it is strange when I commit from my laptop (newly installed) it says it's committed by that guy... I have to review git settings...

strange... Or is your secret alter ego 😁?

> As per testing... I was unable to fully compile due to a problem with TCatSysManagerLib.dll

I'm trying to get the pipelines to run. For this I manually added the .dll at a certain point. Now I put the original reference back again (see 54e768d955193996e0714ed3459d2094f7a43bc3). I guess you were trying with a version before that. It also failed at a certain point for me. 

> Anyways, I never had a problem with an extension adding edition (there could be a problem with versions, though)... so better we test it...

Good to know! 👍

**Comment by PTKu** [comment]
@Roald87  added pre-requisites for VS2019. The extension installs into Pro correctly now. I will test more later this week.

**Comment by PTKu** [comment]
OK, @Roald87 I did test it on VS2019 Pro and it works like magic. I will leave in the Enterprise edition as well, I do not expect troubles, did not have an opportunity to test, if there is a bug it will be on me 😄. 
Setting for review...

**Comment by Roald87** [comment]
Thanks for checking it! I've added the supported versions to [the release notes](https://github.com/Roald87/TcBlack/releases/tag/TcBlackExtension_v0.1.0).

**Pull request merged**
